### ISSUE TITLE
[LB Installer] Error when installing EAN animation data on EAN files modified with YaEAN

### ISSUE THREAD

**Issue by UnleashedGH** [LazyBone152/XV2-Tools#17]
New EAN code seems to have compatibility issues with files modified with YaEAN, this is a problem in regards to installing new data to CMN.ean

XV2 Serializer will just hang on an infinite loop
while the Installer spits this log

```
System.Exception: Failed at EAN install phase (CMN/CMN.ean.xml). ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Xv2CoreLib.EAN.EAN_Node.LinkEskData(ESK_Skeleton skeleton) in C:\Users\Unleashed\Documents\GitHub\XV2-Tools\Xv2CoreLib\EAN\EAN_File.cs:line 1164
   at Xv2CoreLib.EAN.EAN_Animation.LinkEskData(ESK_Skeleton skeleton) in C:\Users\Unleashed\Documents\GitHub\XV2-Tools\Xv2CoreLib\EAN\EAN_File.cs:line 574
   at Xv2CoreLib.EAN.EAN_File.LinkEskData() in C:\Users\Unleashed\Documents\GitHub\XV2-Tools\Xv2CoreLib\EAN\EAN_File.cs:line 111
   at LB_Mod_Installer.Installer.Install.GetParsedFileFromGame(String path, Xv2FileIO fileIO, Boolean onlyFromCpk, Boolean raiseEx)
   at LB_Mod_Installer.Installer.Install.GetParsedFile[T](String path, Boolean fromCpk, Boolean raiseEx)
   at LB_Mod_Installer.Installer.Install.Install_EAN(String xmlPath, String installPath, Boolean isXml)
   --- End of inner exception stack trace ---
   at LB_Mod_Installer.Installer.Install.Install_EAN(String xmlPath, String installPath, Boolean isXml)
   at LB_Mod_Installer.Installer.Install.StartInstall()
   at LB_Mod_Installer.Installer.Install.Start()
```

this issue is regarding this line
`EskRelativeTransform = esk?.RelativeTransform;`

not sure what's wrong, it's as if the null check isn't really working
i tried the traditional If statement check aswell with the same issue

**Comment by LazyBone152** [comment]
That's pretty odd. I can't seem to reproduce the issue on my end either... but the ESK linking can just be disabled for installing and XMLing since it doesn't serve a purpose there. It's just there to easily get the default bone values for animation playback.

No point wasting time trying to fix it when its not needed.
