### ISSUE TITLE
LB Mod Installer [Enhancement]: Include existing chara slots in x2s file

### ISSUE THREAD

**Issue by Sportiax** [LazyBone152/XV2-Tools#20]
Wondering if the next update could allow already existing chara slots to be edited with LB Mod Installer?

Here's the error I got using version 3.85:
System.Exception: Failed at CharaSlots install phase (XV2P_SLOTS.x2s.xml). ---> System.Exception: Attempted to install a slot that already existed.
   at LB_Mod_Installer.Installer.Install.Install_CharaSlots(String xmlPath)
   --- End of inner exception stack trace ---
   at LB_Mod_Installer.Installer.Install.Install_CharaSlots(String xmlPath)
   at LB_Mod_Installer.Installer.Install.StartInstall()
   at LB_Mod_Installer.Installer.Install.Start()
   
   Also, could XV2P_SLOTS_STAGE.x2s & XV2P_SLOTS_STAGE_LOCAL.x2s be included in the next update?

**Comment by LazyBone152** [comment]
feature added in 3.10.0
