### ISSUE TITLE
The file is too long. This operation is currently limited to supporting files less than 2 gigabytes in size.

### ISSUE THREAD

**Issue by goilup** [LazyBone152/XV2-Tools#49]
Hi I am trying to import an acb that imports an awb with it, and I can not import it due to this. Is this something that can be fixed?

The AWB file is nearly 3GB being imported, and the ACB file is only 81KB.

> System.IO.IOException: The file is too long. This operation is currently limited to supporting files less than 2 gigabytes in size.
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Xv2CoreLib.ACB.ACB_File.Load(String path, Boolean writeXml) in C:\source\XenoverseTools\XV2 Tools\Xv2CoreLib\ACB\ACB_File.cs:line 259
   at AudioCueEditor.MainWindow.<>c__DisplayClass28_0.<LoadAcb>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AudioCueEditor.MainWindow.<LoadAcb>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by LazyBone152** [comment]
This should now load in 1.0, but I have no suitable awb to test with so I cant confirm it.

**Comment by Crafty-The-Fox** [comment]
it loads fine in 1.0.0

**Comment by LazyBone152** [comment]
Does it save, and then load again properly?

**Comment by Crafty-The-Fox** [comment]
i think it does? still has issues in game but that might just be format issues. It dosent make all sound silent like before.
